/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones =
  | 'Pacific/Midway'
  | 'Pacific/Niue'
  | 'Pacific/Honolulu'
  | 'Pacific/Rarotonga'
  | 'America/Anchorage'
  | 'Pacific/Gambier'
  | 'America/Los_Angeles'
  | 'America/Tijuana'
  | 'America/Denver'
  | 'America/Phoenix'
  | 'America/Chicago'
  | 'America/Guatemala'
  | 'America/New_York'
  | 'America/Bogota'
  | 'America/Caracas'
  | 'America/Santiago'
  | 'America/Buenos_Aires'
  | 'America/Sao_Paulo'
  | 'Atlantic/South_Georgia'
  | 'Atlantic/Azores'
  | 'Atlantic/Cape_Verde'
  | 'Europe/London'
  | 'Europe/Berlin'
  | 'Africa/Lagos'
  | 'Europe/Athens'
  | 'Africa/Cairo'
  | 'Europe/Moscow'
  | 'Asia/Riyadh'
  | 'Asia/Dubai'
  | 'Asia/Baku'
  | 'Asia/Karachi'
  | 'Asia/Tashkent'
  | 'Asia/Calcutta'
  | 'Asia/Dhaka'
  | 'Asia/Almaty'
  | 'Asia/Jakarta'
  | 'Asia/Bangkok'
  | 'Asia/Shanghai'
  | 'Asia/Singapore'
  | 'Asia/Tokyo'
  | 'Asia/Seoul'
  | 'Australia/Brisbane'
  | 'Australia/Sydney'
  | 'Pacific/Guam'
  | 'Pacific/Noumea'
  | 'Pacific/Auckland'
  | 'Pacific/Fiji';

export interface Config {
  auth: {
    users: UserAuthOperations;
  };
  blocks: {};
  collections: {
    services: Service;
    sectors: Sector;
    projects: Project;
    testimonials: Testimonial;
    faqs: Faq;
    enquiries: Enquiry;
    media: Media;
    users: User;
    'payload-kv': PayloadKv;
    'payload-locked-documents': PayloadLockedDocument;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  collectionsJoins: {};
  collectionsSelect: {
    services: ServicesSelect<false> | ServicesSelect<true>;
    sectors: SectorsSelect<false> | SectorsSelect<true>;
    projects: ProjectsSelect<false> | ProjectsSelect<true>;
    testimonials: TestimonialsSelect<false> | TestimonialsSelect<true>;
    faqs: FaqsSelect<false> | FaqsSelect<true>;
    enquiries: EnquiriesSelect<false> | EnquiriesSelect<true>;
    media: MediaSelect<false> | MediaSelect<true>;
    users: UsersSelect<false> | UsersSelect<true>;
    'payload-kv': PayloadKvSelect<false> | PayloadKvSelect<true>;
    'payload-locked-documents': PayloadLockedDocumentsSelect<false> | PayloadLockedDocumentsSelect<true>;
    'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
    'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: number;
  };
  fallbackLocale: null;
  globals: {
    'site-settings': SiteSetting;
  };
  globalsSelect: {
    'site-settings': SiteSettingsSelect<false> | SiteSettingsSelect<true>;
  };
  locale: null;
  widgets: {
    collections: CollectionsWidget;
  };
  user: User;
  jobs: {
    tasks: unknown;
    workflows: unknown;
  };
}
export interface UserAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
/**
 * What Dainamo does. Flagship services lead the home page.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "services".
 */
export interface Service {
  id: number;
  title: string;
  /**
   * The web address for this page. Generated automatically, but you can edit it.
   */
  slug?: string | null;
  /**
   * Short label used in menus and cards. Example: "Epoxy flooring".
   */
  shortName?: string | null;
  /**
   * One or two sentences. Appears on cards and in search results.
   */
  summary: string;
  heroImage?: (number | null) | Media;
  /**
   * The full explanation of the service.
   */
  body?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  /**
   * The specific products or methods used, and where each one suits.
   */
  systems?:
    | {
        name: string;
        detail?: string | null;
        id?: string | null;
      }[]
    | null;
  scopeIncludes?:
    | {
        item: string;
        id?: string | null;
      }[]
    | null;
  /**
   * Which building types this service is most often specified for.
   */
  sectors?: (number | Sector)[] | null;
  /**
   * Flagship services appear in the main capability sequence on the home page. Keep this to four.
   */
  flagship?: boolean | null;
  /**
   * Lower numbers appear first.
   */
  order?: number | null;
  /**
   * Optional. A single number that makes the service concrete.
   */
  metric?: {
    value?: string | null;
    unit?: string | null;
    caption?: string | null;
  };
  /**
   * Leave blank and the page will use its own heading and intro. Fill these in only when you want tighter control.
   */
  seo?: {
    /**
     * Around 55 to 60 characters reads best in Google.
     */
    title?: string | null;
    /**
     * One or two plain sentences. Around 150 characters.
     */
    description?: string | null;
    /**
     * A single self contained paragraph that answers "what is this and who is it for". AI assistants quote this, so avoid marketing language.
     */
    answer?: string | null;
    /**
     * Used when the page is shared on WhatsApp, LinkedIn or Facebook.
     */
    image?: (number | null) | Media;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * Photography and documents used across the website.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media".
 */
export interface Media {
  id: number;
  /**
   * Describe what is in the picture for screen readers and search engines. Example: "Epoxy floor coating applied in a hospital corridor".
   */
  alt: string;
  /**
   * Optional photographer or source credit.
   */
  credit?: string | null;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
  sizes?: {
    thumb?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    card?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    wide?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    hero?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
  };
}
/**
 * The kinds of buildings Dainamo works in. Each one gets its own page.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "sectors".
 */
export interface Sector {
  id: number;
  title: string;
  /**
   * The web address for this page. Generated automatically, but you can edit it.
   */
  slug?: string | null;
  summary: string;
  image?: (number | null) | Media;
  /**
   * The real constraints on site. Trading hours, infection control, forklift traffic, and so on.
   */
  pressures?:
    | {
        title: string;
        detail?: string | null;
        id?: string | null;
      }[]
    | null;
  body?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  /**
   * The services most often specified for this sector.
   */
  services?: (number | Service)[] | null;
  order?: number | null;
  /**
   * Controls how large this sector appears in the home page grid.
   */
  featureSpan?: ('standard' | 'wide' | 'tall') | null;
  /**
   * Leave blank and the page will use its own heading and intro. Fill these in only when you want tighter control.
   */
  seo?: {
    /**
     * Around 55 to 60 characters reads best in Google.
     */
    title?: string | null;
    /**
     * One or two plain sentences. Around 150 characters.
     */
    description?: string | null;
    /**
     * A single self contained paragraph that answers "what is this and who is it for". AI assistants quote this, so avoid marketing language.
     */
    answer?: string | null;
    /**
     * Used when the page is shared on WhatsApp, LinkedIn or Facebook.
     */
    image?: (number | null) | Media;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * Completed work. Only publish a project once the client is happy for it to be shown.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "projects".
 */
export interface Project {
  id: number;
  title: string;
  /**
   * The web address for this page. Generated automatically, but you can edit it.
   */
  slug?: string | null;
  /**
   * Leave blank if the client has not agreed to be named.
   */
  client?: string | null;
  location?: string | null;
  completedOn?: string | null;
  summary: string;
  brief?: string | null;
  approach?: string | null;
  outcome?: string | null;
  beforeImage?: (number | null) | Media;
  afterImage?: (number | null) | Media;
  gallery?:
    | {
        image: number | Media;
        id?: string | null;
      }[]
    | null;
  facts?:
    | {
        value: string;
        label: string;
        id?: string | null;
      }[]
    | null;
  services?: (number | Service)[] | null;
  sector?: (number | null) | Sector;
  /**
   * Featured projects appear on the home page. Keep this to one or two.
   */
  featured?: boolean | null;
  /**
   * Projects without consent stay hidden from the website.
   */
  clientConsent?: boolean | null;
  /**
   * Leave blank and the page will use its own heading and intro. Fill these in only when you want tighter control.
   */
  seo?: {
    /**
     * Around 55 to 60 characters reads best in Google.
     */
    title?: string | null;
    /**
     * One or two plain sentences. Around 150 characters.
     */
    description?: string | null;
    /**
     * A single self contained paragraph that answers "what is this and who is it for". AI assistants quote this, so avoid marketing language.
     */
    answer?: string | null;
    /**
     * Used when the page is shared on WhatsApp, LinkedIn or Facebook.
     */
    image?: (number | null) | Media;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * Short quotes from clients. Three lines at most, or they will be cut off.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "testimonials".
 */
export interface Testimonial {
  id: number;
  /**
   * Keep it under about 30 words so it reads at a glance.
   */
  quote: string;
  author: string;
  role?: string | null;
  organisation?: string | null;
  order?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * Real questions clients ask. These are read by Google and by AI assistants, so answer them plainly and completely.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "faqs".
 */
export interface Faq {
  id: number;
  /**
   * Write it the way a client would ask it.
   */
  question: string;
  /**
   * Answer in the first two sentences, then add detail. Do not promise prices or guarantees that have not been agreed.
   */
  answer: string;
  topic?: ('general' | 'commercial' | 'site' | 'technical' | 'contracts') | null;
  /**
   * Show this question on the home page. Six is a comfortable maximum.
   */
  showOnHome?: boolean | null;
  order?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * Site assessment requests submitted from the website.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "enquiries".
 */
export interface Enquiry {
  id: number;
  contactName: string;
  organisation?: string | null;
  email: string;
  phone: string;
  siteLocation?: string | null;
  sectorType?: string | null;
  service?: string | null;
  message?: string | null;
  status?: ('new' | 'contacted' | 'booked' | 'quoted' | 'won' | 'closed') | null;
  /**
   * Which page the enquiry came from.
   */
  source?: string | null;
  /**
   * Not visible to the client.
   */
  notes?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * People who can sign in to the Dainamo content studio.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users".
 */
export interface User {
  id: number;
  /**
   * Shown in the studio header and on audit trails.
   */
  name: string;
  role?: ('owner' | 'editor') | null;
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  sessions?:
    | {
        id: string;
        createdAt?: string | null;
        expiresAt: string;
      }[]
    | null;
  password?: string | null;
  collection: 'users';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv".
 */
export interface PayloadKv {
  id: number;
  key: string;
  data:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: number;
  document?:
    | ({
        relationTo: 'services';
        value: number | Service;
      } | null)
    | ({
        relationTo: 'sectors';
        value: number | Sector;
      } | null)
    | ({
        relationTo: 'projects';
        value: number | Project;
      } | null)
    | ({
        relationTo: 'testimonials';
        value: number | Testimonial;
      } | null)
    | ({
        relationTo: 'faqs';
        value: number | Faq;
      } | null)
    | ({
        relationTo: 'enquiries';
        value: number | Enquiry;
      } | null)
    | ({
        relationTo: 'media';
        value: number | Media;
      } | null)
    | ({
        relationTo: 'users';
        value: number | User;
      } | null);
  globalSlug?: string | null;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: number;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: number;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "services_select".
 */
export interface ServicesSelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  shortName?: T;
  summary?: T;
  heroImage?: T;
  body?: T;
  systems?:
    | T
    | {
        name?: T;
        detail?: T;
        id?: T;
      };
  scopeIncludes?:
    | T
    | {
        item?: T;
        id?: T;
      };
  sectors?: T;
  flagship?: T;
  order?: T;
  metric?:
    | T
    | {
        value?: T;
        unit?: T;
        caption?: T;
      };
  seo?:
    | T
    | {
        title?: T;
        description?: T;
        answer?: T;
        image?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "sectors_select".
 */
export interface SectorsSelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  summary?: T;
  image?: T;
  pressures?:
    | T
    | {
        title?: T;
        detail?: T;
        id?: T;
      };
  body?: T;
  services?: T;
  order?: T;
  featureSpan?: T;
  seo?:
    | T
    | {
        title?: T;
        description?: T;
        answer?: T;
        image?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "projects_select".
 */
export interface ProjectsSelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  client?: T;
  location?: T;
  completedOn?: T;
  summary?: T;
  brief?: T;
  approach?: T;
  outcome?: T;
  beforeImage?: T;
  afterImage?: T;
  gallery?:
    | T
    | {
        image?: T;
        id?: T;
      };
  facts?:
    | T
    | {
        value?: T;
        label?: T;
        id?: T;
      };
  services?: T;
  sector?: T;
  featured?: T;
  clientConsent?: T;
  seo?:
    | T
    | {
        title?: T;
        description?: T;
        answer?: T;
        image?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "testimonials_select".
 */
export interface TestimonialsSelect<T extends boolean = true> {
  quote?: T;
  author?: T;
  role?: T;
  organisation?: T;
  order?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "faqs_select".
 */
export interface FaqsSelect<T extends boolean = true> {
  question?: T;
  answer?: T;
  topic?: T;
  showOnHome?: T;
  order?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "enquiries_select".
 */
export interface EnquiriesSelect<T extends boolean = true> {
  contactName?: T;
  organisation?: T;
  email?: T;
  phone?: T;
  siteLocation?: T;
  sectorType?: T;
  service?: T;
  message?: T;
  status?: T;
  source?: T;
  notes?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media_select".
 */
export interface MediaSelect<T extends boolean = true> {
  alt?: T;
  credit?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
  sizes?:
    | T
    | {
        thumb?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        card?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        wide?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        hero?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users_select".
 */
export interface UsersSelect<T extends boolean = true> {
  name?: T;
  role?: T;
  updatedAt?: T;
  createdAt?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  loginAttempts?: T;
  lockUntil?: T;
  sessions?:
    | T
    | {
        id?: T;
        createdAt?: T;
        expiresAt?: T;
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv_select".
 */
export interface PayloadKvSelect<T extends boolean = true> {
  key?: T;
  data?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T;
  globalSlug?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * Contact details, service areas and the words used across the website.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "site-settings".
 */
export interface SiteSetting {
  id: number;
  legalName?: string | null;
  tagline?: string | null;
  phones?:
    | {
        label?: string | null;
        number: string;
        id?: string | null;
      }[]
    | null;
  email?: string | null;
  whatsapp?: string | null;
  address?: {
    street?: string | null;
    suburb?: string | null;
    city?: string | null;
    province?: string | null;
    postalCode?: string | null;
  };
  openingHours?:
    | {
        days?: string | null;
        opens?: string | null;
        closes?: string | null;
        id?: string | null;
      }[]
    | null;
  /**
   * Towns and suburbs Dainamo covers. These are used by Google and AI assistants to decide whether to recommend the company for a local search.
   */
  serviceAreas?:
    | {
        name: string;
        id?: string | null;
      }[]
    | null;
  /**
   * One paragraph on travel, call out and coverage outside Gauteng.
   */
  coverageNote?: string | null;
  /**
   * Only list a client here once you have their permission to show their name publicly.
   */
  clients?:
    | {
        name: string;
        logo?: (number | null) | Media;
        permissionConfirmed?: boolean | null;
        id?: string | null;
      }[]
    | null;
  commitments?:
    | {
        title: string;
        detail?: string | null;
        id?: string | null;
      }[]
    | null;
  /**
   * Company registration number. Leave blank until confirmed.
   */
  registrationNumber?: string | null;
  /**
   * Tick only once VAT registration is confirmed.
   */
  vatRegistered?: boolean | null;
  vatNumber?: string | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "site-settings_select".
 */
export interface SiteSettingsSelect<T extends boolean = true> {
  legalName?: T;
  tagline?: T;
  phones?:
    | T
    | {
        label?: T;
        number?: T;
        id?: T;
      };
  email?: T;
  whatsapp?: T;
  address?:
    | T
    | {
        street?: T;
        suburb?: T;
        city?: T;
        province?: T;
        postalCode?: T;
      };
  openingHours?:
    | T
    | {
        days?: T;
        opens?: T;
        closes?: T;
        id?: T;
      };
  serviceAreas?:
    | T
    | {
        name?: T;
        id?: T;
      };
  coverageNote?: T;
  clients?:
    | T
    | {
        name?: T;
        logo?: T;
        permissionConfirmed?: T;
        id?: T;
      };
  commitments?:
    | T
    | {
        title?: T;
        detail?: T;
        id?: T;
      };
  registrationNumber?: T;
  vatRegistered?: T;
  vatNumber?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "collections_widget".
 */
export interface CollectionsWidget {
  data?: {
    [k: string]: unknown;
  };
  width: 'full';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}


declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}